services:
  - type: web
    name: avito-book-bot
    env: python
    buildCommand: pip install --no-build-isolation -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PIP_NO_BINARY
        value: :all:
